// Create Comment
export const COMMENT__CREATE_REQUEST = "COMMENT__CREATE_REQUEST";
export const COMMENT__CREATE_SUCCESS = "COMMENT__CREATE_SUCCESS";
export const COMMENT__CREATE_FAIL = "COMMENT__CREATE_FAIL";
export const COMMENT__CREATE_RESET = "COMMENT__CREATE_RESET";