// Create Post
export const POST__CREATE_REQUEST = "POST__CREATE_REQUEST";
export const POST__CREATE_SUCCESS = "POST__CREATE_SUCCESS";
export const POST__CREATE_FAIL = "POST__CREATE_FAIL";
export const POST__CREATE_RESET = "POST__CREATE_RESET";

// Get All Posts
export const POST__GET_ALL_REQUEST = "POST__GET_ALL_REQUEST";
export const POST__GET_ALL_SUCCESS = "POST__GET_ALL_SUCCESS";
export const POST__GET_ALL_FAIL = "POST__GET_ALL_FAIL";
export const POST__GET_ALL_RESET = "POST__GET_ALL_RESET";

// Get Post
export const POST__GET_REQUEST = "POST__GET_REQUEST";
export const POST__GET_SUCCESS = "POST__GET_SUCCESS";
export const POST__GET_FAIL = "POST__GET_FAIL";
export const POST__GET_RESET = "POST__GET_RESET";

// Update Post
export const POST__UPDATE_REQUEST = "POST__UPDATE_REQUEST";
export const POST__UPDATE_SUCCESS = "POST__UPDATE_SUCCESS";
export const POST__UPDATE_FAIL = "POST__UPDATE_FAIL";
export const POST__UPDATE_RESET = "POST__UPDATE_RESET";

// Delete Post
export const POST__DELETE_REQUEST = "POST__DELETE_REQUEST";
export const POST__DELETE_SUCCESS = "POST__DELETE_SUCCESS";
export const POST__DELETE_FAIL = "POST__DELETE_FAIL";
export const POST__DELETE_RESET = "POST__DELETE_RESET";
